apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: kubelet-access-role
rules:
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/metrics"]
    verbs: ["get", "list"]
